In [2]:
import numpy as np

In [ ]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [ ]:
myarray = np.array(a)
myarray

array([1, 2, 3, 4, 5])

In [ ]:
myarray = np.array([2,4,6,8,10])
myarray

array([ 2,  4,  6,  8, 10])

In [ ]:
# creating 2 dimentional array 
a = [[1,2,3,],[4,5,6],[7,8,9]]
my_ar2 = np.array(a)
my_ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# how to take value from user 
a=[]
n = int(input(" enter the size of the array "))
for i in range(n):
  value = int(input("enter the value"))
  a.append(value)
my_ar = np.array(a)
my_ar

 enter the size of the array 5
enter the value1
enter the value2
enter the value3
enter the value4
enter the value5


array([1, 2, 3, 4, 5])

In [ ]:
print("total dimensions:",my_ar2.ndim)

total dimensions: 2


In [ ]:
print("shape of array :",my_ar2.shape)

shape of array : (3, 3)


In [ ]:
# built function in numpy 
# zeros 
arr = np.zeros(5)  # for single dimensions array 
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr_z = np.zeros((2,3))
arr_z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
## ones
arr_ones = np.ones(4) 
arr_ones


array([1., 1., 1., 1.])

In [ ]:
arr_ones2 = np.ones((2,3))
arr_ones2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# eye function : its create an array with all diagonal elements a 1 and remaining as 0 
arr_eye = np.eye(3)
arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr_2 = np.eye(3,4) # this is for non square matrix 
arr_2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# diag , its create a array with all diagonal elements , and remaining elements are zero 
b = np.diag([1,2,3,4])
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#### to get the digonal elements 
np.diag(b)

array([1, 2, 3, 4])

In [ ]:
#    randint its used to generate a random number between a given range 
# syntax rand(min,max,total_value,total_value)
arr = np.random.randint(1,10,3)
arr


array([5, 3, 4])

In [ ]:
## rand , this value used to generate random no between 0 to one ; 
arr = np.random.rand(4)
arr

array([0.0438121 , 0.79869961, 0.91948214, 0.62199689])

In [ ]:
# (randn) this function  used to generate random number close to zero 
arr = np.random.randn(3)
arr

array([ 0.47132596, -0.97364716, -0.31342404])

In [ ]:
# indexing and slicing in python 
a = []
n = int(input("enter the size of the array:"))
for i in range(n):
  val = int(input("enter the value:"))
  a.append(val)
arr = np.array(a)
 
for i in range(arr.size):
  print(arr[i])
sum1 =0 
for i in range(arr.size):
  sum1=sum1+arr[i]  
print(sum1)


enter the size of the array:5
enter the value:1
enter the value:2
enter the value:3
enter the value:4
enter the value:5
1
2
3
4
5
15


In [ ]:
## indexing and slicing are same as list  in array 


In [ ]:
# reshaping of array 
arr= np.random.randint(1,100,12)
b= arr.reshape(3,4)
b



array([[14, 90, 77, 66],
       [25, 51, 46, 11],
       [21, 34, 34, 52]])

In [ ]:
b=b.reshape(12)  # from two dimentional to 1 dimensional array 
b


array([14, 90, 77, 66, 25, 51, 46, 11, 21, 34, 34, 52])

In [ ]:
## if you provide -1 in place of rows and columns it will take automatically by its own 
b =b.reshape(3,-1)
b

array([[14, 90, 77, 66],
       [25, 51, 46, 11],
       [21, 34, 34, 52]])

In [ ]:
# seed function in numpy  used to fixed the value of random function 
# np.random.seed(a)   a can be any number ,
np.random.seed(6)

c = np.random.randint(1,100,12)
c= c.reshape(4,3)
c


array([[11, 74, 85],
       [80, 81, 63],
       [26,  2, 76],
       [78, 58, 27]])

In [ ]:
##### creating two dimensional array 
import numpy as np

In [ ]:
matrix = []
row = int(input("enter row number:"))
col = int(input("enter col number:"))
for i in range(row):
  a = []
  for j in range(col):
    val = int(input("enter the value"))
    a.append(val)
  matrix.append(a)
arr = np.array(matrix)
for i in range(row):
  for j in range(col):
    print(arr[i][j],end=" ")
  print()

enter row number:3
enter col number:3
enter the value1
enter the value2
enter the value3
enter the value4
enter the value5
enter the value6
enter the value7
enter the value8
enter the value9
1 2 3 
4 5 6 
7 8 9 


In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# slicing of two dimensional array 
# syntax a[row_range,col_range]
arr[:2]     # here only row no is provided , it will take the value of 0 and 1 , rows 2 excluded 

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[ :2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
arr[: :, 0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#  view and copy , when we do slicing and create   a sub array any changes on sub array changes the original array too, 
# but using copy it dosen change the original array 
slicing = arr[:2,:2].copy()
slicing[:] = 0
slicing

array([[0, 0],
       [0, 0]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
### numpy conditional selection 
a = np.arange(1,16)
a                              # arange is also use to create an array 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
b =a[a%2==0]
b

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
##333   operations on array 
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [ ]:
# in numpy array divide by zero gives infinity result , and not zero 
# add the individual values of array 
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)
arr1 + arr2

array([ 6,  8, 10, 12])

In [ ]:
# operations on 2 dimensional array 
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)
a + b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
### np.argmin(a)  it will give the index of min value in array a 
# np.sqrt(a) square root of every element 
# np.linspace(1,2,5)    it returns the value between a given range with equal range  it will also include the last value 
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# axis = 1 row and axis = 0 is column 
a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.min(a)

1

In [ ]:
np.sum(a)

45

In [ ]:
np.max(a)

9

In [ ]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.sum(a,axis=1)    # it gives the row wise sum 

array([10, 26, 42])

In [ ]:
np.sum(a,axis=0)              # it gives the column wise sum 

array([15, 18, 21, 24])

In [ ]:
np.random.seed(122)
matrix = np.random.randint(1,21,10)
np.random.shuffle(matrix)
matrix

array([13, 16, 16, 11, 16, 10, 11, 13, 17,  3])

In [ ]:
np.unique(matrix)        # remove all duplicates and give unique number 

array([ 3, 10, 11, 13, 16, 17])

In [ ]:
matrix

array([13, 16, 16, 11, 16, 10, 11, 13, 17,  3])

In [ ]:
np.unique(matrix,return_index=True,return_counts=True)

(array([ 3, 10, 11, 13, 16, 17]),
 array([9, 5, 3, 0, 1, 8]),
 array([1, 1, 2, 2, 3, 1]))

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# searching in array 
b = np.array([1,2,3,4,5,6,7,8,9])
np.where(b==4)

(array([3]),)

In [4]:
c = np.array([2,3,5,7,8])
np.searchsorted(c,4)

2

In [ ]:
#### creation of array 
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
### concatenate
np.concatenate((np.arange(3),np.arange(5)))

array([0, 1, 2, 0, 1, 2, 3, 4])

In [ ]:
a 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
b = np.arange(1,10).astype(int)         #### astype is used to change the value into int and float and in str
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b.reshape(3,3)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# a = np.nonzero(b<5)
# hsplit, vsplit

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(2, 2, 3)

In [ ]:
###Access the third element of the second array of the first array:
print(arr[0, 1, 2])

6


**Iterating Arrays Using nditer()**

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


**Iterate through every scalar element of the 2D array skipping 1 element:**


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for y, x in np.ndenumerate(arr):
  print(y, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
def print_full_name(first, last):
    
    print('Hello', a ,b+'!','You just delved into python.')
a= input() 
b= input()
print_full_name(a, b)

sonu
kumar
Hello sonu kumar! You just delved into python.


In [ ]:
import numpy as np

In [ ]:
print(np.char.add(['hello',"sonu"],["abc",'xyz']))

['helloabc' 'sonuxyz']


In [ ]:
print(np.char.center('hello',20,fillchar = "-"))

-------hello--------


In [ ]:
np.char.strip(["sonu","neha","naina"],"a")

array(['sonu', 'neh', 'nain'], dtype='<U5')

In [9]:
x= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [10]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
x.shape

(2, 2, 3)

In [12]:
x.ndim

3