In [3]:
import csv

In [ ]:
### question 1 

In [4]:
with open('sales.csv','r') as f:
  reader = csv.reader(f)
  l=[]
  for i in reader:
    l.append(i)

In [5]:
for j in l[:10]:
  print(j)

['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount', 'Profit']
['Second Class', 'Consumer', 'United States', 'Henderson', 'Kentucky', '42420', 'South', 'Furniture', 'Bookcases', '261.96', '2', '0', '41.9136']
['Second Class', 'Consumer', 'United States', 'Henderson', 'Kentucky', '42420', 'South', 'Furniture', 'Chairs', '731.94', '3', '0', '219.582']
['Second Class', 'Corporate', 'United States', 'Los Angeles', 'California', '90036', 'West', 'Office Supplies', 'Labels', '14.62', '2', '0', '6.8714']
['Standard Class', 'Consumer', 'United States', 'Fort Lauderdale', 'Florida', '33311', 'South', 'Furniture', 'Tables', '957.5775', '5', '0.45', '-383.031']
['Standard Class', 'Consumer', 'United States', 'Fort Lauderdale', 'Florida', '33311', 'South', 'Office Supplies', 'Storage', '22.368', '2', '0.2', '2.5164']
['Standard Class', 'Consumer', 'United States', 'Los Angeles', 'California', '90032', 'West', 'Fu

In [ ]:
#question 2 

In [11]:
import csv                             #writing in csv by using writerow()
with open('sales_summary.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["States", "Total_quantity", "Total_profit"])
    writer.writerow(["bihar", 10, "10%"])
    writer.writerow(["up", 15, "15%"])

    

In [10]:
# (q8)Create a 4*5 array with 1 on the border and 0 inside
import numpy as np
arr_z = np.zeros((4,5))
arr_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
### Q8
b= np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,0,0,1],[1,1,1,1,1]])
b


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [17]:
#Print all columns except the first and the last in the above matrix. 
b[: :,1:4]

array([[1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

In [ ]:
# 
