In [1]:
import numpy as np

In [6]:
###1. Write a NumPy program to compute the multiplication of two given matrices
a = np.arange(1,6)
b = np.arange(6,11)
print(a*b)



[ 6 14 24 36 50]


In [9]:
##2. Write a NumPy program to compute the outer product of two given vectors.
a = np.arange(1,6)
b = np.arange(6,11)
result = np.outer(a,b)
print(result)
print(a)
print(b)

[[ 6  7  8  9 10]
 [12 14 16 18 20]
 [18 21 24 27 30]
 [24 28 32 36 40]
 [30 35 40 45 50]]
[1 2 3 4 5]
[ 6  7  8  9 10]


In [22]:
#Q3 3. Write a NumPy program to compute the cross product of two given vectors.
c = np.array([1,2,3])
d = np.array([4,5,6])
result = np.cross(c,d)
print(result)

[-3  6 -3]


In [23]:
###4. Write a NumPy program to compute the determinant of a given square array.
a = np.array([[1, 0], [1, 2]])
print(a)
print(np.linalg.det(a))

[[1 0]
 [1 2]]
2.0


In [28]:
#5. Write a NumPy program to evaluate Einstein's summation convention of two given
#multidimensional arrays.
#
a = np.array([1,2,3])
b = np.array([4,5,6])
result =  np.einsum("n,n", a, b)
print(result)




32


In [30]:
#6. Write a NumPy program to compute the inner product of vectors for 1-D arrays (without
#complex conjugation)
#and in higher dimension.
a = np.array([1,2,3])
b = np.array([4,5,6])
result = np.inner(a, b)
print(result)


32


In [32]:
#7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given
#square array.
m = np.mat("4 -2;1 2")
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix",v)

Eigenvalues of the said matrix [3.+1.j 3.-1.j]
Eigenvectors of the said matrix [[0.81649658+0.j         0.81649658-0.j        ]
 [0.40824829-0.40824829j 0.40824829+0.40824829j]]


In [35]:
#8. Write a NumPy program to compute the Kronecker product of two given mulitdimension
#arrays.
a = np.array([1,2,3])
b = np.array([4,5,6])

result =  np.kron(a, b)
print(result)

[ 4  5  6  8 10 12 12 15 18]


In [39]:
###9. Write a NumPy program to compute the condition number of a given matrix.
import numpy as np
from numpy import linalg as LA
a = np.array([[1, 2, -3], [4, 1, 5], [1, 0, 1]])
print("Original matrix:")
print(a.shape)
print(a.ndim)
print("The condition number of the said matrix:")
print(LA.cond(a))

Original matrix:
(3, 3)
2
The condition number of the said matrix:
26.17838834272503


In [40]:
#10. Write a NumPy program to find a matrix or vector norm.
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)

Vector norm:
9.539392014169456
Matrix norm:
5.477225575051661


In [41]:
#11. Write a NumPy program to compute the determinant of an array.
a = np.array([[3,2],[4,5]])
print(a)
result =  np.linalg.det(a)
print(result)


[[3 2]
 [4 5]]
6.999999999999999


In [42]:
#12. Write a NumPy program to compute the inverse of a given matrix
m = np.array([[1,2],[3,4]])

print(m)
result =  np.linalg.inv(m)

print(result)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [43]:
#13. Write a NumPy program to calculate the QR decomposition of a given matrix.
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
print(m.ndim)
result =  np.linalg.qr(m)
print("Decomposition of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
2
Decomposition of the said matrix:
(array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


In [45]:
#14. Write a NumPy program to compute the condition number of a given matrix.
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original matrix:")
print(m)
result =  np.linalg.cond(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Condition number of the said matrix:
3.813147060626918e+16


In [48]:
#15. Write a NumPy program to compute the sum of the diagonal element of a given array.
m = np.arange(9).reshape(3,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Condition number of the said matrix:
12
